// pravin's  patashala all Rights Reserved 

#pragma once
#include "NativeGameplayTags.h"


namespace WarriorGameplayTags
{
	/* Input Tags */
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);

	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equip_Axe);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Unequip_Axe);

	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equip_FrostGiant);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Unequip_FrostGiant);

	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Equip_DualBladeAxe1);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Unequip_DualBladeAxe1);

	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_LightAttack_Axe);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_HeavyAttack_Axe);



	/* Player Weapons Tags */
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_FrostGiant);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_DualBladeAxe1);

	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_FrostGiant);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_DualBladeAxe1);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_LightAttack_Axe);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HeavyAttack_Axe);

	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_FrostGiant);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_DualBladeAxe1);

	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_FrostGiant);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_DualBladeAxe1);

	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_FrostGiant);
	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_DualBladeAxe1);


	ADVANCEDRPG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);




}
